# Cluster Analysis

## Metode berhirarki

Ref:
https://rpubs.com/odenipinedo/cluster-analysis-in-R


```{r}
library(readxl)
Provinsi <- read_excel("Data/provinsi.xlsx")
Prov.scaled = scale(Provinsi[,c(4:8)])
rownames(Prov.scaled) = Provinsi$Provinsi
head(Prov.scaled)
```

```{r}
## membuat dissimilarity matrix
dprov = dist(Prov.scaled, method="euclidean")
```

```{r}
c.comp = hclust(dprov, method = "complete")
cor(dprov , cophenetic(c.comp))
```

```{r}
c.sing = hclust(dprov, method = "single")
cor(dprov , cophenetic(c.sing))
```

```{r}
c.avrg = hclust(dprov, method = "average")
cor(dprov , cophenetic(c.avrg))
```

```{r}
c.ward = hclust(dprov, method = "ward.D")
cor(dprov , cophenetic(c.ward))
```


```{r}
c.ctrd = hclust(dprov, method = "centroid")
cor(dprov , cophenetic(c.ctrd))
```

```{r}
library(factoextra)
fviz_dend(c.avrg, cex = 0.5, 
          main = "Cluster Dendrogram average linkage")
```

```{r}
avg_coph <- cophenetic(c.avrg)
avg_clust <- cutree(c.avrg, k = 4)
table(avg_clust)
```

```{r}
fviz_dend(c.avrg, k = 4, 
          k_colors = "jco", 
          rect = T, 
          main = "Average Linkage Cluster")
```

```{r}
library(clValid)
library(cluster)
# internal measures
internal <- clValid(Prov.scaled, nClust = 2:6, 
                    clMethods = "hierarchical", 
                    validation = "internal", 
                    metric = "euclidean",
                    method = "average")
summary(internal)
```

```{r}
fviz_dend(c.avrg, k = 2, 
          k_colors = "jco", 
          rect = T, 
          main = "Average Linkage Cluster")
```

```{r}
group = cutree(c.avrg, k = 2)
group
```

```{r}
fviz_cluster(list(data = Prov.scaled, 
                  cluster = group)) + 
  theme_minimal()
```

```{r}
prcomp(Prov.scaled)
```

## Metode tidak berhirarki - kmeans

```{r}
fviz_nbclust(Prov.scaled, kmeans, method = "wss")
```

```{r}
fviz_nbclust(Prov.scaled, kmeans, method = "silhouette")
```

```{r}
set.seed(1)
km = kmeans(Prov.scaled, centers=4)
km
```

```{r}
fviz_cluster(list(data = Prov.scaled, cluster = km$cluster)) + theme_minimal()
```
